### ISSUE TITLE
[1.12.2] Crashed with sponge

### ISSUE THREAD

**Issue by SettingDust** [Fuzss/fivefeetsmall#21]
```
[21:21:08] [main/INFO] [mixin]: Instancing error handler class org.spongepowered.mod.mixin.handler.MixinErrorHandler
[21:21:08] [main/FATAL] [mixin]: Mixin apply failed META-INF/mixins.aquaacrobatics.json:EntityPlayerMixin -> net.minecraft.entity.player.EntityPlayer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/entity/player/EntityPlayer::setSizeWakeUpPlayer with priority 1000 cannot inject into net/minecraft/entity/player/EntityPlayer::func_70999_a(ZZZ)V merged by org.spongepowered.mod.mixin.core.entity.player.EntityPlayerMixin_Forge with priority 1001 [PREINJECT Applicator Phase -> META-INF/mixins.aquaacrobatics.json:EntityPlayerMixin -> Prepare Injections ->  -> redirect$bcn000$setSizeWakeUpPlayer(Lnet/minecraft/entity/player/EntityPlayer;FF)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/entity/player/EntityPlayer::setSizeWakeUpPlayer with priority 1000 cannot inject into net/minecraft/entity/player/EntityPlayer::func_70999_a(ZZZ)V merged by org.spongepowered.mod.mixin.core.entity.player.EntityPlayerMixin_Forge with priority 1001 [PREINJECT Applicator Phase -> META-INF/mixins.aquaacrobatics.json:EntityPlayerMixin -> Prepare Injections ->  -> redirect$bcn000$setSizeWakeUpPlayer(Lnet/minecraft/entity/player/EntityPlayer;FF)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:367) ~[%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1244) ~[%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) [%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [%5B%5Dspongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_275]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_275]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [?:1.8.0_275]
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048) [?:1.8.0_275]
	at java.lang.Class.getMethod0(Class.java:3018) [?:1.8.0_275]
	at java.lang.Class.getMethod(Class.java:1784) [?:1.8.0_275]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2847-universal.jar:?]
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [META-INF/mixins.aquaacrobatics.json:EntityPlayerMixin] from phase [DEFAULT] in config [META-INF/mixins.aquaacrobatics.json] FAILED during APPLY
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.getMethod0(Class.java:3018)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.getMethod(Class.java:1784)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[21:21:08] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/entity/player/EntityPlayer::setSizeWakeUpPlayer with priority 1000 cannot inject into net/minecraft/entity/player/EntityPlayer::func_70999_a(ZZZ)V merged by org.spongepowered.mod.mixin.core.entity.player.EntityPlayerMixin_Forge with priority 1001 [PREINJECT Applicator Phase -> META-INF/mixins.aquaacrobatics.json:EntityPlayerMixin -> Prepare Injections ->  -> redirect$bcn000$setSizeWakeUpPlayer(Lnet/minecraft/entity/player/EntityPlayer;FF)V -> Prepare]
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:367)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1244)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	... 20 more
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: java.lang.reflect.InvocationTargetException
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.Class.getMethod0(Class.java:3018)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at java.lang.Class.getMethod(Class.java:1784)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:21:08] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: 	... 6 more
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	... 13 more
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	... 15 more
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [META-INF/mixins.aquaacrobatics.json:EntityPlayerMixin] from phase [DEFAULT] in config [META-INF/mixins.aquaacrobatics.json] FAILED during APPLY
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	... 20 more
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/entity/player/EntityPlayer::setSizeWakeUpPlayer with priority 1000 cannot inject into net/minecraft/entity/player/EntityPlayer::func_70999_a(ZZZ)V merged by org.spongepowered.mod.mixin.core.entity.player.EntityPlayerMixin_Forge with priority 1001 [PREINJECT Applicator Phase -> META-INF/mixins.aquaacrobatics.json:EntityPlayerMixin -> Prepare Injections ->  -> redirect$bcn000$setSizeWakeUpPlayer(Lnet/minecraft/entity/player/EntityPlayer;FF)V -> Prepare]
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:367)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1244)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[21:21:08] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	... 20 more
```

**Comment by mo0dss** [comment]
Can you post a list of mods you're using alongside aquatic acrobatics?

**Comment by SettingDust** [comment]
@Moodsss None. Tested :D.

**Comment by mo0dss** [comment]
@SettingDust so the issue is fixed?

**Comment by SettingDust** [comment]
@Moodsss nope

**Comment by mo0dss** [comment]
@SettingDust Try removing spongeforge, its patching the same area as aquatic acrobatics is

**Comment by Fuzss** [comment]
How is [this version](https://mega.nz/file/nZ8SjICa#OeRunSRyNLeZopRv9XTGbbwceEbd93xDvavjQEoq0uw) working for you?

**Comment by Fuzss** [comment]
Sorry, wrong button.

**Comment by KookosPahkina** [comment]
I have this same issue, and i cant remove spongeforge because i need it for the server.

**Comment by Fuzss** [comment]
> I have this same issue, and i cant remove spongeforge because i need it for the server.

Try the test version I provided above and report back.

**Comment by KookosPahkina** [comment]
> > I have this same issue, and i cant remove spongeforge because i need it for the server.
> 
> Try the test version I provided above and report back.

It did not work, crashed on start up
https://pastebin.com/wZAjiVW6
there is the latest log from the server, however i am running a bunch of other mods as well since I'm running rebirth of the night pack but the server works if aqua acrobatics is disabled, using spongeforge 1.12.2-2838-7.3.0 and  forge-1.12.2-14.23.5.2854.jar

**Comment by Fuzss** [comment]
How about [this](https://mega.nz/file/GcN2yBoB#-Uhr-tDK_UHYbeJpslHiQDIFroXKSZQjID6O6BxcFl8)?

**Comment by KookosPahkina** [comment]
> How about [this](https://mega.nz/file/GcN2yBoB#-Uhr-tDK_UHYbeJpslHiQDIFroXKSZQjID6O6BxcFl8)?

https://pastebin.com/jPanMQHc , no luck :/

**Comment by Fuzss** [comment]
Sorry, that couldn't have worked anyways. I didn't read the crash-log properly. So how about [this one](https://mega.nz/file/fRVyALgT#0QeX-u_TXTOTagMe9NJqehsr-sl6JFX0rjHHQGU25YU) now? :D

**Comment by SettingDust** [comment]
> Sorry, that couldn't have worked anyways. I didn't read the crash-log properly. So how about [this one](https://mega.nz/file/fRVyALgT#0QeX-u_TXTOTagMe9NJqehsr-sl6JFX0rjHHQGU25YU) now? :D

It's ok now. The sponge can start up normally.
