### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by Carvercarver1** [Fuzss/fivefeetsmall#47]
Either I'm silly, or something doesn't seem to work properly as it crashes on startup. Is there any particular reason for crash or coremod is absent?  If so, which coremod I need to install?

=======================================================
[19:13:42] [main/WARN] [FML]: The coremod Aqua Acrobatics Transformer (com.fuzs.aquaacrobatics.core.AquaAcrobaticsCore) is not signed!
[19:13:42] [main/ERROR] [Aqua Acrobatics Transformer]: No instance of Mixin framework detected. Unable to proceed load.
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_51]
	at com.fuzs.aquaacrobatics.core.AquaAcrobaticsCore.<init>(AquaAcrobaticsCore.java:36) [AquaAcrobatics-1.5.2.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_51]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:594) [forge-1.12.2-14.23.5.2857.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) [forge-1.12.2-14.23.5.2857.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) [forge-1.12.2-14.23.5.2857.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) [forge-1.12.2-14.23.5.2857.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) [forge-1.12.2-14.23.5.2857.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) [forge-1.12.2-14.23.5.2857.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) [forge-1.12.2-14.23.5.2857.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 19 more

**Comment by embeddedt** [comment]
Install MixinBootstrap (or another mod which provides a Mixin implementation).

**Comment by Carvercarver1** [comment]
MixinBootstrap, as I saw it, only for 1.15+, there is no version for 1.12. May I have links instead?

**Comment by embeddedt** [comment]
The same JAR works on 1.12. https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap/files/3437402

**Comment by Carvercarver1** [comment]
Oh, right. For some reason website did not show this to me. Will test it. 

In the meantime, this mod also seems to work in case first one fails. https://ru-minecraft.ru/mody-minecraft/68597-mixin.html. Found it... after some searching.

**Comment by Carvercarver1** [comment]
Seems to work, after hitting it with a wrench a good amount of times. For now.

For anyone using vanillafix and reading this, try next: 
try renaming the vanilla fix jar "_aaaVanillaFix-1.0.10-150.jar". If it crashed before, then it means you have a problem with mixin's and another mod is loading an incompatible mixin before vanilla fix (which needs a newer mixin) can be loaded. Force vanillafix to load first by renaming it (it loads in alphabetical order).

**Comment by embeddedt** [comment]
Glad you fixed it!
