### ISSUE TITLE
Crash when opening controls menu

### ISSUE THREAD

**Issue by v1993** [Fuzss/fivefeetsmall#71]
Got new AA version for testing #30 and it crashes if I try to open controls menu.

[crash-2022-02-06_22.19.40-client.txt](https://github.com/Fuzss/aquaacrobatics/files/8011056/crash-2022-02-06_22.19.40-client.txt)

**Comment by embeddedt** [comment]
Fixed in 1.10.1. Thank you.

-----

For a future mod dev who might stumble across a crash report like this:

```
java.lang.NullPointerException
    at net.minecraft.client.gui.GuiListExtended.updateItemPos(SourceFile:30)
    at net.minecraft.client.gui.GuiSlot.drawSelectionBox(GuiSlot.java:457)
    at net.minecraft.client.gui.GuiSlot.drawScreen(GuiSlot.java:247)
    at net.minecraft.client.gui.GuiControls.drawScreen(GuiControls.java:137)
```

don't construct a `KeyBinding` if you're not going to register it ([source](https://github.com/SlimeKnights/TinkersConstruct/issues/945#issuecomment-54667662)).
